name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-backend:
    name: Build .NET Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --configuration Release --no-restore
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build-artifacts
        path: |
          **/bin/Release/**
          **/obj/Release/**
        retention-days: 1

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./client
      run: npm ci
      
    - name: Build frontend
      working-directory: ./client
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-artifacts
        path: |
          client/dist/**
        retention-days: 1

  build-status:
    name: Build Status
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    if: always()
    
    steps:
    - name: Check build results
      run: |
        if [[ "${{ needs.build-backend.result }}" != "success" ]]; then
          echo "❌ Backend build failed"
          exit 1
        fi
        if [[ "${{ needs.build-frontend.result }}" != "success" ]]; then
          echo "❌ Frontend build failed"
          exit 1
        fi
        echo "✅ All builds successful"